name: pytest

on:
  pull_request:
    branches: ["main"]
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "restgdf/**"
      - "tests/**"

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: pip
    - name: Install Python libraries
      run: |
        pip install --user -r requirements.txt
    - name: "Run tests"
      run: |
        coverage run
        coverage report -m --format=markdown
